- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Include Variables
      include_vars: linux_vars.yml
      tags: 
        - include_vars

    - name: Get User
      command: whoami
      register: username
      tags:
        - get_user_name
      changed_when: False

    - debug:
        msg: "[I] Current User: {{ username.stdout }}"
      tags:
        - get_user_name

### Files and Dirs ###
    - name: Create directories
      file:
        path: "~/{{ item }}"
        state: directory
      loop: "{{ directories|flatten(levels=1) }}"
      tags: 
        - create_directories

### Installs ###
    - name: Install Apt Packages
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ apt_installs|flatten(levels=1) }}"
      tags:
        - install_apt_packages

    - name: Install pip packages
      pip:
        name: "{{ item }}"
      become: yes
      become_method: sudo
      loop: "{{ pip_tools|flatten(levels=1) }}"
      tags:
        - install_pip_tools
    
    - name: Clone Config Repo
      git:
        repo: "{{ item }}"
        dest: "~/.cfg"
        clone: yes
        bare: yes
        update: yes
      loop:
        - 'git@github.com:the-real-cphillips/config.git'
      notify:
        - Source Config
      tags:
        - clone_config

    - name: Install Plugins/Tools From Git
      git:
        repo: "{{ item.repo_url }}"
        dest: "{{ item.dest }}"
        update: yes
      loop: "{{ git_tools }}"
      tags:
        - install_from_git

### Handlers ###
  handlers:
    - name: Source Config
      command: . ../dotfiles.sh
