- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Include Variables
      include_vars: vars.yml
      tags: 
        - include_vars

    - name: Get User
      command: whoami
      register: username
      tags:
        - get_user_name
      changed_when: False

    - debug:
        msg: "[I] Current User: {{ username.stdout }}"
      tags:
        - get_user_name

    - name: Create directories
      file:
        path: "~/{{ item }}"
        state: directory
      loop: "{{ directories|flatten(levels=1) }}"
      tags: 
        - create_directories

    - name: Tap Homebrew repositories
      homebrew_tap:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_repos|flatten(levels=1) }}"
      tags:
        - tap_homebrew

    - name: Install tools with homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_tools|flatten(levels=1) }}"
      tags:
        - install_homebrew_tools

    - name: Install homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: installed
      loop: "{{ homebrew_casks|flatten(levels=1) }}"
      tags:
        - install_homebrew_casks

    - name: Install pip packages
      pip:
        name: "{{ item }}"
      become: yes
      become_method: sudo
      loop: "{{ pip_tools|flatten(levels=1) }}"
      tags:
        - install_pip_tools
    
    - name: Clone Config Repo
      git:
        repo: "{{ item }}"
        dest: "~/.cfg"
        clone: yes
        bare: yes
        update: yes
      loop:
        - 'git@github.com:the-real-cphillips/config.git'
      notify:
        - Source Config
      tags:
        - clone_config

    - name: Install TPM
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
        update: yes
      tags:
        - install_tpm

    - name: Install Powerlevel9k
      git:
        repo: https://github.com/bhilburn/powerlevel9k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
        update: yes
      tags:
        - install_p9k

    - name: Build vimrc with plugins
      template:
        src: templates/vimrc.j2
        dest: "~/.vimrc"
        owner: "{{ username.stdout }}"
        mode: 0744
      notify:
        - Install Vim Plugins

  handlers:
    - name: Source Config
      command: source ../dotfiles.sh

    - name: Install Vim Plugins
      command: vim +PlugInstall +qall
