- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Include Variables
      include_vars: vars.yml
      tags: 
        - include_vars

    - name: Get User
      command: whoami
      register: username
      tags:
        - get_user_name
      changed_when: False

    - debug:
        msg: "[I] Current User: {{ username.stdout }}"
      tags:
        - get_user_name

### Files and Dirs ###
    - name: Create directories
      file:
        path: "~/{{ item }}"
        state: directory
      loop: "{{ directories|flatten(levels=1) }}"
      tags: 
        - create_directories

    - name: Copy Docker Config.json for Credential Helper
      copy:
        dest: "~/.docker/config.json"
        src: files/docker-config.json
        owner: "{{ username.stdout }}"
        mode: 0744
      tags:
        - copy_docker_config_json
          
    - name: Tap Homebrew repositories
      homebrew_tap:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_repos|flatten(levels=1) }}"
      tags:
        - tap_homebrew

### Installs ###
    - name: Install tools with homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrew_tools|flatten(levels=1) }}"
      tags:
        - install_homebrew_tools

    - name: Install homebrew casks
      homebrew_cask:
        name: "{{ item }}"
        state: installed
      loop: "{{ homebrew_casks|flatten(levels=1) }}"
      tags:
        - install_homebrew_casks

    - name: Install pip packages
      pip:
        name: "{{ item }}"
      become: yes
      become_method: sudo
      loop: "{{ pip_tools|flatten(levels=1) }}"
      tags:
        - install_pip_tools
    
    - name: Clone Config Repo
      git:
        repo: "{{ item }}"
        dest: "~/.cfg"
        clone: yes
        bare: yes
        update: yes
      loop:
        - 'git@github.com:the-real-cphillips/config.git'
      notify:
        - Source Config
      tags:
        - clone_config

    - name: Install Plugins/Tools From Git
      git:
        repo: "{{ item.repo_url }}"
        dest: "{{ item.dest }}"
        update: yes
      loop: "{{ git_tools }}"
      tags:
        - install_from_git

    - name: Build vimrc with plugins
      template:
        src: templates/vimrc.j2
        dest: "~/.vimrc"
        owner: "{{ username.stdout }}"
        mode: 0744
      notify:
        - Install Vim Plugins

### Handlers ###
  handlers:
    - name: Source Config
      command: . ../dotfiles.sh

    - name: Install Vim Plugins
      command: vim +PlugInstall +qall
