---
name: Run ShellCheck

on: [push]

jobs:
    shellcheck:
      name: Shellcheck
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Run ShellCheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@master
