---
name: Run ShellCheck

on: [push]

jobs:
    shellcheck:
      name: Shellcheck
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: tty
        continue-on-error: true

      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const CODE = '```';
            const output = `
            <details>
            <summary>Output</summary>
            ${CODE}
            ${{ steps.shellcheck.outputs.stdout }}
            ${CODE}
            </details>`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
