---
name: Run ShellCheck

on: [push]

jobs:
    shellcheck:
      name: Shellcheck
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: tty
        continue-on-error: true

      - uses: actions/github-script@v3
        if: github.event_name == 'pull_request' || github.event_name == 'push' && steps.sc.outcome == 'failure' 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const CODE = '```';
            const STATUS = ":x: **Failure**, Please check your Script"
            const output = `
            ${STATUS}
            <details>
            <summary>Output</summary>
            ${CODE}
            ${{ steps.sc.outputs.files }}
            ${CODE}
            </details>`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: End Result
        shell: bash
        run: |
          echo ${{ steps.sc.outcome }}
          echo ${{ steps.sc.outputs }}
          echo "shellcheck"
          test ${{ steps.sc.conclusion }} == 
